# Generated by Django 6.0.3 on 2026-05-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://designshack.net/wp-content/uploads/Free-Simple-Restaurant-Logo-Template.jpg', max_length=400),
        ),
    ]
